name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Install LLVM 22
      run: |
        wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 22
        sudo apt-get install -y libpolly-22-dev
        echo "LLVM_SYS_221_PREFIX=/usr/lib/llvm-22" >> $GITHUB_ENV
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run Clippy
      run: cargo +nightly clippy --verbose --no-deps
    - name: Run tests
      run: cargo +nightly test --verbose
    - name : Check Format
      run: cargo +nightly fmt --verbose --check
